version: "3"

services:
  # backend:
  #   build: .
  #   image: jangmin/backend
  #   links: 
  #     - postgres:postgres
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - .env.production
  #   depends_on:
  #     - postgres
  #   networks:
  #     - postgres

  # nginx:
  #   build: .
  #   image: jangmin/nginx
  #   ports:
  #     - "8000:443"
  #   networks:
  #     - postgres

  postgres:
    image: postgres:14
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/postgres
    env_file:
      - .env.development

  pgadmin:
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    env_file:
      - .env.development
    depends_on:
      - postgres
    networks:
      - postgres 

networks:
  postgres:
    driver: bridge